toiExecutorConfig:
  data: toiExecutorConfigData 
  fromToiPackageExecutorConfig: (( stub(toiPackageExecutorConfig) ))
  fromLibrary1: (( stub(toiExecutorTemplateLibrary1) ))
  fromLibrary2: (( stub(toiExecutorTemplateLibrary2) )) 
